# Generated by Django 6.0.6 on 2026-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_providerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='office_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
