worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name _;

        add_header Cross-Origin-Opener-Policy "same-origin-allow-popups";

        # Frontend React App
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Django Admin & Django Static Files
        location /admin/ {
            proxy_pass http://admin:8080/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /static/ {
            proxy_pass http://admin:8080/static/;
            proxy_set_header Host $host;
        }

        # FastAPI Backend
        location /api/ {
            proxy_pass http://backend:8001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
