# Generated by Django 6.0.6 on 2026-06-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_provider_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='maternal_last_name',
        ),
    ]
