# Generated by Django 6.0.6 on 2026-06-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_maternal_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maternal_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
